version: "3.9"
services:

  # Laravel application
  php-fpm:
    container_name: php-fpm_todo_list
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    #depends_on:
    # - mysql
    networks:
      - todo_api_network

  # Web server
  nginx:
    image: nginx:alpine
    container_name: nginx_todo_list
    volumes:
        - .:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
        #- ./storage/logs/nginx:/var/log/nginx
    ports:
      - "8001:80"
    #depends_on:
    # - php-fpm
    networks:
      - todo_api_network

# MySQL Database
  mysql:
      container_name: mysql_todo_list
      image: mysql:8.0.20
      #volumes:
      #    - ./storage/mysql-data:/var/lib/mysql
      ports:
          - "3306:3306"
      environment:
          MYSQL_DATABASE: todo_list
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root
      networks:
          - todo_api_network
networks:
  todo_api_network:
